[tool.poetry]
name = "zing"
version = "0.1.0"
description = ""
authors = ["pratikmain2525 <m25297251@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic-settings = "2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
